### PR TITLE
Sort lists inside json if sort option is enabled

### PR DESCRIPTION
**Pull request by utkarshgupta137**

### CODE REVIEW

**Comment by utkarshgupta137** [comment]
@lexicalunit

**Comment by lexicalunit** [comment]
Unfortunately changing the order of arrays can affect program behavior. For example, prettier doesn't do this: https://github.com/prettier/prettier/issues/3569

**Comment by utkarshgupta137** [comment]
Would it be reasonable to allow it as a setting?

**Comment by lexicalunit** [comment]
Maybe! It would have to have a warning about how it could cause issues. Also there would need to be some added unit tests with the change.

**Pull request closed without merging**
