### PR TITLE
Allow notification on parse errors.

### LINKED ISSUE #29: How to use it?
downloaded and installed in Atom.

In a new json file, selected the whole flat codes, and hit Package > Pretty JSON > Prettify, but nothing changed...

What's the right method?

### PR DESCRIPTION
**Pull request by lexicalunit**
- Resolves some coffeescript style issues. Such as removes unnecessary
  `;`, `()`, and uses single quotes for string literals.
- Adds `atom.notifications` code to error catch code.
- Adds `notifyOnParseError` configuration option, default to `true`.
- Updates README.md with additional feature information.
- Adds missing "Sort and Prettify" menu command.

This should resolve #29 as a lot of the confusion about this package not
working is likely due to parse issues.

### CODE REVIEW

**Comment by federomero** [comment]
Thank you for your PR! Are you by any chance interested in maintaining this project? I started this a while back to toy around with atom but it got more attention than I expected and I don't really have much time to dedicate to this.

**Comment by lexicalunit** [comment]
I would be happy to! How do you want to handle the transfer?

**Comment by federomero** [comment]
I just added you as a collaborator to this project since it was the easiest thing to do. This should allow you to publish the package too. I would say we try this for a while and then I can transfer the ownership of the repository if you prefer that. What do you think?

**Comment by lexicalunit** [comment]
Sounds good to me!

**Pull request merged**
